specVersion: 1.0.0
name: stake-indexer
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be used as a starting point for developing your SubQuery
  project
repository: "https://github.com/subquery/subql-starter"
schema:
  file: ./schema.graphql
network:
  # The genesis hash of the network (hash of block 0)
  chainId: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint:
    - wss://polkadot.api.onfinality.io/public-ws
    - wss://rpc.polkadot.io
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://api.subquery.network/sq/subquery/polkadot-dictionary"
dataSources:
  - kind: substrate/Runtime
    startBlock: 15115880
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRewardPayout
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleAccountGain
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleChildBountiesAdded
          kind: substrate/EventHandler
          filter:
            module: childBounties
            method: Added
        - handler: handleChildBountiesClaimed
          kind: substrate/EventHandler
          filter:
            module: childBounties
            method: Claimed